apiVersion: v1
kind: Service
metadata:
  name: account-query
  namespace: thinkdemo
spec:
  selector:
    app: account-query-selector
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
