apiVersion: v1
kind: Service
metadata:
  name: account-command
  namespace: thinkdemo
spec:
  selector:
    app: account-command-selector
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

